config/routes.rb
Frenzy::Application.routes.draw do
  resources :leagues, except: [:show]
  resources :periods, except: [:new]
  resources :clubs do
    collection do
      get :index
      post :index
    end
  end
  resources :newsitems do
    resources :comments
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get :silent
    end
  end
  resources :visits do
    collection do
      get :all_maps
    end
  end

  namespace :clubs_frenzy do

  end

  resources :results do
    collection do
      post :store_all
      post :scrape
      get :index
      post :index
    end
  end
  resources :gamerounds
  resources :selections
  resources :jokers do
    post :store, on: :collection
  end
  resources :scores do
    collection do
      get :index
      post :index
    end
  end
  resources :rankings do
    collection do
      get :index
      post :index
      get :period
      get :general
    end
  end

  resources :registrations, only: [:register_user] do
    collection do
      get  :register_user
      post :process_user
    end
  end

  get  "frenzy/index"
  get  "frenzy/rules"
  get  "frenzy/about"
  post "frenzy/process_gameround"
  post "frenzy/switch_period"
  post "frenzy/switch_participation"
  post "frenzy/cancel_jokers"

  get "site/index"

  match '/sign_out', to:  "clearance/sessions#destroy"

  match "/404", to: "errors#not_found"
  match "/403", to: "errors#not_authorized"
  match "/500", to: "errors#internal_server_error"

  root to:'site#index'
end

app/models/league.rb
# == Schema Information
#
# Table name: leagues
#
#  id           :integer          not null, primary key
#  league_name  :string(255)
#  league_short :string(255)
#  level        :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class League < ActiveRecord::Base
  has_many :clubs

  attr_accessible :league_name, :league_short, :level
  validates :league_name, :league_short, :level, presence: true
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_filter :authorize
  load_and_authorize_resource

  def index
    @leagues = League.all
  end

  def new
    @league = League.new
  end

  def edit
    @league = League.find(params[:id])
  end

  def create
    @league = League.new(params[:league])

    if @league.save
      redirect_to leagues_path, notice: 'League was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @league = League.find(params[:id])

    if @league.update_attributes(params[:league])
      redirect_to leagues_path, notice: 'League was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @league = League.find(params[:id])
    @league.destroy

    redirect_to leagues_path, notice: 'League was successfully deleted.'
  end
end

app/views/leagues/_form.html.haml
= form_for @league, html: { class: 'form-horizontal' } do |f|
  = render "layouts/error_messages", target: @league
  .control-group
    = f.label I18n.t('.league.league_name')
    = f.text_field :league_name
  .control-group
    = f.label I18n.t('.league.league_short')
    = f.text_field :league_short
  .control-group
    = f.label I18n.t('.league.level')
    = f.text_field :level
  .control-group
    .controls
      = f.submit(value: I18n.t('.general.save'), class: 'btn')
      = link_to t('.cancel', default: t("helpers.links.cancel")), leagues_path, class: 'btn'

app/views/leagues/edit.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.league.edit')
    = render partial: "form"

app/views/leagues/index.html.haml
- model_class = League
.row
  .span12
    .page-header
      %h1=t '.title', default: model_class.model_name.human.pluralize
    %table.table.table-striped
      %thead
        %tr
          %th= model_class.human_attribute_name(:id)
          %th= model_class.human_attribute_name(:league_name)
          %th= model_class.human_attribute_name(:league_short)
          %th= model_class.human_attribute_name(:level)
          - if can? :update, League
            %th=t '.actions', default: t("helpers.actions")
      %tbody
        - @leagues.each do |league|
          %tr
            %td= league.id
            %td= league.league_name
            %td= league.league_short
            %td= league.level
            - if can? :update, League
              %td
                = link_to t('.edit', default: t("helpers.links.edit")), edit_league_path(league), class: 'btn btn-mini'
                = link_to t('.destroy', default: t("helpers.links.destroy")), league_path(league), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger'

    - if can? :create, League
      = link_to t('.new', default: t("helpers.links.new")), new_league_path, class: 'btn'

app/views/leagues/new.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.league.new')
    = render partial: "form"