config/routes.rb
Frenzy::Application.routes.draw do
  resources :leagues, except: [:show]
  resources :periods, except: [:new]
  resources :clubs do
    collection do
      get :index
      post :index
    end
  end
  resources :newsitems do
    resources :comments
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get :silent
    end
  end
  resources :visits do
    collection do
      get :all_maps
    end
  end

  namespace :clubs_frenzy do

  end

  resources :results do
    collection do
      post :store_all
      post :scrape
      get :index
      post :index
    end
  end
  resources :gamerounds
  resources :selections
  resources :jokers do
    post :store, on: :collection
  end
  resources :scores do
    collection do
      get :index
      post :index
    end
  end
  resources :rankings do
    collection do
      get :index
      post :index
      get :period
      get :general
    end
  end

  resources :registrations, only: [:register_user] do
    collection do
      get  :register_user
      post :process_user
    end
  end

  get  "frenzy/index"
  get  "frenzy/rules"
  get  "frenzy/about"
  post "frenzy/process_gameround"
  post "frenzy/switch_period"
  post "frenzy/switch_participation"
  post "frenzy/cancel_jokers"

  get "site/index"

  match '/sign_out', to:  "clearance/sessions#destroy"

  match "/404", to: "errors#not_found"
  match "/403", to: "errors#not_authorized"
  match "/500", to: "errors#internal_server_error"

  root to:'site#index'
end

app/models/visit.rb
# == Schema Information
#
# Table name: visits
#
#  id         :integer          not null, primary key
#  visit_nr   :integer
#  visit_date :datetime
#  league     :string(255)
#  home_club  :string(255)
#  away_club  :string(255)
#  ground     :string(255)
#  street     :string(255)
#  city       :string(255)
#  country    :string(255)
#  longitude  :float
#  latitude   :float
#  gmaps      :boolean
#  result     :string(255)
#  season     :string(255)
#  kickoff    :string(255)
#  gate       :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Visit < ActiveRecord::Base
  belongs_to :user

  acts_as_gmappable

  attr_accessible :away_club, :city, :gate, :ground, :home_club, :kickoff, :latitude, :longitude, :gmaps, :league, :result,
                  :season, :street, :country, :user_id, :visit_date, :visit_nr

  validates :city, :street, :country, :ground, :result, :visit_nr, :visit_date, presence: true

  def gmaps4rails_address
    "#{self.street}, #{self.city}, #{self.country}"
  end

  def gmaps4rails_infowindow
    "<p>#{self.home_club}</p>
     <p>#{self.ground}</p>
     <p><a href='/visits/#{self.id}'>view details</a></p>"
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_filter :authorize
  load_and_authorize_resource

  def index
    if params[:user]
      visits = User.find(params[:user]).visits.order("visit_nr DESC")
    else
      visits = current_user.visits.order("visit_nr DESC")
    end
    @map_visits = visits.to_gmaps4rails
    @list_visits = visits
  end

  def all_maps
    @users = User.all
  end

  def new
    @visit = Visit.new
    @visit_nr = current_user.visits.count + 1
  end

  def edit
    @visit = Visit.find(params[:id])
    @visit_nr = @visit.visit_nr
  end

  def create
    @visit = Visit.new(params[:visit])

    if @visit.save
      redirect_to visits_path, notice: I18n.t('.visit.created')
    else
      render action: "new"
    end
  end

  def update
    @visit = Visit.find(params[:id])

    if @visit.update_attributes(params[:visit])
      redirect_to visits_path, notice: I18n.t('.visit.updated')
    else
      render action: "edit"
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    redirect_to visits_path, notice: I18n.t('.visit.deleted')
  end
end

app/views/visits/_form.html.haml
.row
  .offset1.span10
    = form_for @visit, html: { class: "form-horizontal"} do |f|
      = render "layouts/error_messages", target: @visit
      = f.hidden_field :user_id, value: current_user.id
      .control-group
        = f.label I18n.t('.visit.form.visit_nr')
        = f.text_field :visit_nr, class: "input-mini", value: @visit_nr
      .control-group
        = f.label I18n.t('.visit.form.visit_date')
        = f.date_select :visit_date, include_blank: true, start_year: 1950
      .control-group
        = f.label I18n.t('.visit.form.league')
        = f.text_field :league, class: "input-xlarge", placeholder: 'The Championship'
      .control-group
        = f.label I18n.t('.visit.form.home_club')
        = f.text_field :home_club, class: "input-xlarge", placeholder: 'Charlton Athletic'
      .control-group
        = f.label I18n.t('.visit.form.away_club')
        = f.text_field :away_club, class: "input-xlarge", placeholder: 'Millwall'
      .control-group
        = f.label I18n.t('.visit.form.season')
        = f.text_field :season, class: "input-medium", placeholder: '2012-2013'
      .control-group
        = f.label I18n.t('.visit.form.result')
        = f.text_field :result, class: "input-small", placeholder: '2-1'
      .control-group
        = f.label I18n.t('.visit.form.kickoff')
        = f.text_field :kickoff, class: "input-small", placeholder: '15:00'
      .control-group
        = f.label I18n.t('.visit.form.gate')
        = f.text_field :gate, class: "input-small", placeholder: '19645'
      .control-group
        = f.label I18n.t('.visit.form.ground')
        = f.text_field :ground, class: "input-xlarge", placeholder: 'The Valley'
      .control-group
        = f.label I18n.t('.visit.form.street')
        = f.text_field :street, class: "input-xlarge", placeholder: 'Floyd Road'
      .control-group
        = f.label I18n.t('.visit.form.city')
        = f.text_field :city, class: "input-xlarge", placeholder: 'London'
      .control-group
        = f.label I18n.t('.visit.form.country')
        = f.select :country, [ "#{I18n.t('.general.countries.england')}", "#{I18n.t('.general.countries.scotland')}", "#{I18n.t('.general.countries.wales')}", "#{I18n.t('.general.countries.n_ireland')}", "#{I18n.t('.general.countries.ireland')}" ]
      .control-group
        .submit
          = f.submit(class: 'btn', value: I18n.t('.general.save'))

app/views/visits/_visit_list.html.haml
.visits
  %table.table.table-striped
    %thead
      %tr
        %th= I18n.t('.visit.form.visit_nr_short')
        %th.responsive_hide= I18n.t('.visit.form.season')
        %th= I18n.t('.visit.form.visit_date')
        %th.responsive_hide= I18n.t('.visit.form.ground')
        %th= I18n.t('.visit.details.match')
        %th.responsive_hide= I18n.t('.visit.form.result')
        %th
    %tbody
      - unless @list_visits.blank?
        - @list_visits.each do |visit|
          %tr
            = show_table_column(I18n.t('.visit.form.visit_nr_short'), visit.visit_nr)
            = show_table_column(I18n.t('.visit.form.season'), visit.season, true)
            = show_table_column(I18n.t('.visit.form.visit_date'), visit.visit_date.strftime("%d-%m-%Y"), true)
            %td.responsive_hide{ "data-title" => "#{I18n.t('.visit.form.ground')}" }= visit.ground.blank? ? "-" : visit.ground
            %td{ "data-title" => "#{I18n.t('.visit.details.match')}" }
              = visit.home_club.blank? ? "-" : visit.home_club
              v
              = visit.away_club.blank? ? "-" : visit.away_club
            %td.responsive_hide{ "data-title" => "#{I18n.t('.visit.form.result')}" }= visit.result.blank? ? "-" : visit.result
            %td{ "data-title" => "#{I18n.t('.general.actions')}" }
              = link_to I18n.t('.general.details'), visit_path(visit), class: 'btn btn-mini'
  //= will_paginate @list_visits

app/views/visits/all_maps.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.visit.all_maps.title')

.row
  .span12
    %p= I18n.t('.visit.all_maps.intro', total_matches: Visit.all.size)

.row
  - counter = 1
  - @users.each do |user|
    - unless user.visits.blank?
      - map_visits = user.visits
      .span4.map
        .map_details
          %h3= link_to user.team_name, user_path(user)
        %div{ id: "map_#{counter}" }= static_map_for(map_visits)
        .map_more
          %p= link_to I18n.t('.visit.all_maps.details'), visits_path(user: user)
        - counter += counter

app/views/visits/edit.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.visit.edit_visit')

.row
  .span12
    = render partial: "form"

app/views/visits/index.html.haml
.row
  .span12
    .page-header
      - if params[:user]
        %h1= I18n.t('.visit.visit_title', team: User.find(params[:user]).team_name)
      - else
        %h1= I18n.t('.visit.my_visits_title')

    - if can? :create, Visit and params[:user].blank?
      .action= link_to I18n.t('.new', default: I18n.t("helpers.links.new")), new_visit_path, class: 'btn'

.row
  .span12
    %p= I18n.t('.visit.details.intro', number: current_user.visits.size)

.row
  .span12
    %ul#myTab.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#listTab"}= I18n.t('.visit.list')
      %li
        %a{"data-toggle" => "tab", href: "#mapTab"}= I18n.t('.visit.map')
    #myTabContent.tab-content
      #listTab.tab-pane.fade.in.active
        = render "visit_list"
      #mapTab.tab-pane.fade
        - if @map_visits.blank?
          %p= I18n.t('.visit.map')
        - else
          = gmaps("map_options" => {"zoom" => 6}, "markers" => { "data" => @map_visits })

app/views/visits/new.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.visit.new_visit')

.row
  .span12
    = render partial: "form"

app/views/visits/show.html.haml
.row
  .span12
    %p= link_to I18n.t('.visit.details.back'), :back

.row-fluid
  .span10.offset1.club_details
    .span12
      .title= I18n.t('.visit.details.match_details')
    .hero-unit
      .span4
        %ul
          %li= "#{I18n.t('.visit.form.visit_nr')}:"
          %li= "#{I18n.t('.visit.form.league')}:"
          %li= "#{I18n.t('.visit.details.match')}:"
          %li= "#{I18n.t('.visit.form.result')}:"
          %li= "#{I18n.t('.visit.form.gate')}:"
          %li= "#{I18n.t('.visit.form.visit_date')}:"
          %li= "#{I18n.t('.visit.form.kickoff')}:"
          %li= "#{I18n.t('.visit.form.ground')}:"
          %li= "#{I18n.t('.visit.details.location')}:"
      .span8
        %ul
          %li
            = @visit.visit_nr.blank? ? "-" : @visit.visit_nr
            \/
            = current_user.visits.size
          %li= @visit.league.blank? ? "-" : @visit.league
          %li
            = @visit.home_club.blank? ? "-" : @visit.home_club
            v
            = @visit.away_club.blank? ? "-" : @visit.away_club
          %li= @visit.result.blank? ? "-" : @visit.result
          %li= @visit.gate.blank? ? "-" : @visit.gate
          %li= @visit.visit_date.blank? ? "-" : @visit.visit_date.strftime("%d-%m-%Y")
          %li= @visit.kickoff.blank? ? "-" : @visit.kickoff
          %li= @visit.ground.blank? ? "-" : @visit.ground
          %li= "#{@visit.street}, #{@visit.city}, #{@visit.country}"
      .offset4.span5
        - if can? :edit, Visit and current_user.id == @visit.user_id
          .btn= link_to I18n.t('.general.edit'), edit_visit_path(@visit)
          .btn= link_to I18n.t('.destroy', default: t("helpers.links.destroy")), visit_path(@visit), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }
      .clearfix