config/routes.rb
Frenzy::Application.routes.draw do
  resources :leagues, except: [:show]
  resources :periods, except: [:new]
  resources :clubs do
    collection do
      get :index
      post :index
    end
  end
  resources :newsitems do
    resources :comments
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get :silent
    end
  end
  resources :visits do
    collection do
      get :all_maps
    end
  end

  namespace :clubs_frenzy do

  end

  resources :results do
    collection do
      post :store_all
      post :scrape
      get :index
      post :index
    end
  end
  resources :gamerounds
  resources :selections
  resources :jokers do
    post :store, on: :collection
  end
  resources :scores do
    collection do
      get :index
      post :index
    end
  end
  resources :rankings do
    collection do
      get :index
      post :index
      get :period
      get :general
    end
  end

  resources :registrations, only: [:register_user] do
    collection do
      get  :register_user
      post :process_user
    end
  end

  get  "frenzy/index"
  get  "frenzy/rules"
  get  "frenzy/about"
  post "frenzy/process_gameround"
  post "frenzy/switch_period"
  post "frenzy/switch_participation"
  post "frenzy/cancel_jokers"

  get "site/index"

  match '/sign_out', to:  "clearance/sessions#destroy"

  match "/404", to: "errors#not_found"
  match "/403", to: "errors#not_authorized"
  match "/500", to: "errors#internal_server_error"

  root to:'site#index'
end

app/models/clubs_frenzy/result.rb
# == Schema Information
#
# Table name: results
#
#  id           :integer          not null, primary key
#  home_club_id :integer
#  away_club_id :integer
#  home_score   :integer
#  away_score   :integer
#  gameround_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Result < ActiveRecord::Base
  belongs_to :gameround
  belongs_to :home_club, class_name: 'Club'
  belongs_to :away_club, class_name: 'Club'

  attr_accessible :away_club_id, :home_club_id, :gameround_id, :home_score, :away_score
  validates :away_club_id, :home_club_id, :gameround_id, :home_score, :away_score, presence: true

end

app/controllers/clubs_frenzy/results_controller.rb
class ResultsController < ApplicationController
  before_filter :authorize
  load_and_authorize_resource

  def index
    if params[:gameround]
      @current_gameround = Gameround.find(params[:gameround])
      @results = Result.where(gameround_id: params[:gameround])
    else
      @current_gameround = Gameround.where(processed: true).order("id DESC").first
      if @current_gameround.blank?
        @results = Result.order("home_club_id")
      else
        @results = Result.where(gameround_id: @current_gameround.id).order("home_club_id")
      end
    end
    @gamerounds = Gameround.all
  end

  def new
    if params[:results]
      @results = params[:results]
      @gamerounds = Gameround.not_processed
      @clubs = Club.all
    end
    @leagues = League.all
  end

  def edit
    @result = Result.find(params[:id])
  end

  def store_all
    params[:line].each do |counter, line|
      unless line[:home_club_id].blank?
        Result.create(line.merge(gameround_id: params[:gameround_id]))
      end
    end
    redirect_to results_path, notice: "Results #{I18n.t('.created.success')}"
  end

  def update
    @result = Result.find(params[:id])

    if @result.update_attributes(params[:result])
      redirect_to results_path, notice: "Result #{I18n.t('.updated.success')}"
    else
      render action: "edit"
    end
  end

  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    redirect_to results_url
  end

  def scrape
    puts "HUH #{params[:league]}"
    if params[:league]
      thread = Thread.new do
        scraper = Scraper.new(params[:iterations].to_i)
        @results = scraper.get_results(params[:league])
      end
      thread.join
      redirect_to new_result_path(results: @results), notice: "Results collected"
    end
  end
end

app/views/results/edit.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.result.edit')

    = form_for @result, html: { class: 'form-horizontal' } do |f|
      = render "layouts/error_messages", target: @result
      .control-group
        = f.label @result.home_club.club_name
        = f.text_field :home_score, class: "small_text_field"
      .control-group
        = f.label @result.away_club.club_name
        = f.text_field :away_score, class: "small_text_field"
      .control-group
        .controls
          = f.submit :submit, value: I18n.t('.general.save'), class: 'btn'
          = link_to t('.cancel', default: t("helpers.links.cancel")), results_path, class: 'btn'

app/views/results/index.html.haml
.row
  .span12
    = render("shared/gameround_selector", title: I18n.t('.result.results'), intro: nil, target: results_path)

.row
  .span12
    - if can? :create, Result
      .add_record= link_to I18n.t('.new', default: t("helpers.links.new")), new_result_path, class: 'btn'

.row
  .span12
    %table.table.table-striped
      %thead
        %tr
          %th= I18n.t('.league.name')
          %th= I18n.t('.score.match')
          %th= I18n.t('.result.result')
          %th= I18n.t('.gameround.gameround')
          - if can? :update, Result
            %th=t '.actions', default: t("helpers.actions")
      %tbody
        - @results.each do |result|
          %tr
            %td= result.home_club.league.league_short
            %td= "#{result.home_club.club_name} - #{result.away_club.club_name}"
            %td= "#{result.home_score}-#{result.away_score}"
            %td= result.gameround_id
            - if can? :update, Result
              %td
                = link_to I18n.t('.edit', default: t("helpers.links.edit")), edit_result_path(result), class: 'btn btn-mini'
                = link_to I18n.t('.destroy', default: t("helpers.links.destroy")), result_path(result), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger'

app/views/results/new.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.result.new')


- if can? :create, Result
  .row
    .span8.offset3
      .control-group
        .controls
          = form_tag scrape_results_path do
            = text_field_tag :iterations, "1", class: "small_text_field"
            = select_tag :league, options_for_select(@leagues.map{ |l| [l.league_name, l.league_name] })
            = submit_tag :submit, value: I18n.t('.result.scrape'), class: "btn"

    - if @results
      .row
        .span12
          = form_tag store_all_results_path, class: 'form-horizontal' do
            .control-group
              .controls
                = select_tag :gameround_id, options_for_select(@gamerounds.map{ |g| ["#{markup_gameround(g)}", g.id] })

            - counter = 0
            - @results.each do |result|
              .control-group
                .controls
                  = text_field_tag "line[#{counter}][home_club_id]", result["home_club_id"], class: "small_text_field"
                  = label_tag 'home_club', result["home_club"]
                  = text_field_tag "line[#{counter}][away_club_id]", result["away_club_id"], class: "small_text_field"
                  = label_tag 'away_club', result["away_club"]
                  = text_field_tag "line[#{counter}][home_score]", result["home_score"], class: "small_text_field"
                  = text_field_tag "line[#{counter}][away_score]", result["away_score"], class: "small_text_field"
              - counter = counter + 1
            .form-actions
              = submit_tag :submit, value: I18n.t('.general.save'), class: "btn"
              = link_to t('.cancel', default: t("helpers.links.cancel")), results_path, class: 'btn'