config/routes.rb
Frenzy::Application.routes.draw do
  resources :leagues, except: [:show]
  resources :periods, except: [:new]
  resources :clubs do
    collection do
      get :index
      post :index
    end
  end
  resources :newsitems do
    resources :comments
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get :silent
    end
  end
  resources :visits do
    collection do
      get :all_maps
    end
  end

  namespace :clubs_frenzy do

  end

  resources :results do
    collection do
      post :store_all
      post :scrape
      get :index
      post :index
    end
  end
  resources :gamerounds
  resources :selections
  resources :jokers do
    post :store, on: :collection
  end
  resources :scores do
    collection do
      get :index
      post :index
    end
  end
  resources :rankings do
    collection do
      get :index
      post :index
      get :period
      get :general
    end
  end

  resources :registrations, only: [:register_user] do
    collection do
      get  :register_user
      post :process_user
    end
  end

  get  "frenzy/index"
  get  "frenzy/rules"
  get  "frenzy/about"
  post "frenzy/process_gameround"
  post "frenzy/switch_period"
  post "frenzy/switch_participation"
  post "frenzy/cancel_jokers"

  get "site/index"

  match '/sign_out', to:  "clearance/sessions#destroy"

  match "/404", to: "errors#not_found"
  match "/403", to: "errors#not_authorized"
  match "/500", to: "errors#internal_server_error"

  root to:'site#index'
end

app/controllers/clubs_frenzy/frenzy_controller.rb
class FrenzyController < ApplicationController
  before_filter :authorize
  load_and_authorize_resource

  def index
    @gamerounds = Gameround.not_processed
    @clubs = Club.all
    @settings = Setting.first
  end

  def process_gameround
    return unless params[:gameround_id]

    Calculator.new.process_gameround(params[:gameround_id])

    redirect_to frenzy_index_path, notice: t('.frenzy.message_calculated')
  end

  def cancel_jokers
    return unless params[:gameround_id]

    calculator = Calculator.new
    params[:line].each do |counter, line|
      unless line[:home_club_id].blank?
        calculator.cancel_jokers(line.merge(gameround_id: params[:gameround_id]))
      end
    end

    redirect_to frenzy_index_path, notice: t('.frenzy.message_cancelled')
  end

  def rules
  end

  def switch_period
    calculator = Calculator.new
    calculator.switch_period

    redirect_to frenzy_index_path, notice: t('.frenzy.message_period_switched')
  end

  def switch_participation
    setting = Setting.first
    setting.update_attributes(participation: params[:participation])

    redirect_to frenzy_index_path, notice: t('.frenzy.message_participation_switched')
  end

end

app/views/frenzy/_cancel_jokers.html.haml
= form_tag frenzy_cancel_jokers_path, class: 'form-horizontal' do
  .control-group
    .controls
      = select_tag :gameround_id, options_for_select(@gamerounds.map{ |g| ["#{markup_gameround(g)}", g.id] })
  - 1.upto(5) do |counter|
    .control-group
      .controls
      = select_tag "line[#{counter}][home_club_id]", options_for_select(@clubs.map{ |c| [c.club_name, c.id] }), include_blank: true
      = select_tag "line[#{counter}][away_club_id]", options_for_select(@clubs.map{ |c| [c.club_name, c.id] }), include_blank: true
  .form-actions
    = submit_tag :submit, value: I18n.t('.joker.cancel'), class: "btn"
    = link_to t('.cancel', default: t("helpers.links.cancel")), frenzy_index_path, class: 'btn'

app/views/frenzy/about.html.haml
.row
  .span12
    .page-header
      %h1= I18n.t('.frenzy.about_title')

.row
  .span12
    %h2 Waarom de naam "The Old Spotted Dog Frenzy"?

.row
  .span12.about
    .about_section
      %p We zochten de naam van een stadion om voor het woord “Frenzy” neer te zetten. Dan kom je al snel terecht bij de stadions met cultnamen, zoals The Dripping Pan van Lewes, The Giant Axe van Lancaster of The Flying Monk van Malmesbury Victoria, maar de mooiste blijft toch The Old Spotted Dog van Clapton. Daarnaast heeft dat stadion een geschiedenis waar je U tegen zegt en is het vernoemd naar de naastgelegen pub. En wat doe je in pubs buiten boozen? Inderdaad spelletjes. De club, de pub en het stadion hebben het heel zwaar, dus is het wel leuk om wat aandacht aan ze te besteden. Wij hebben namelijk veel sympathie voor de kleine underdog (no pun intended) clubs. Daarom leek de naam “The Old Spotted Dog Frenzy” ons wel heel geschikt. Het lijkt ons ook geweldig om ooit met een aantal deelnemers aan de Frenzy een trip te maken naar Clapton FC en dan The Old Spotted Dog te vincken.

.row
  .span12
    %h2 The Old Spotted Dog

.row
  .span12.about
    .about_section
      %p De pub The Old Spotted Dog is het oudste niet-seculiere gebouw in Newham (Oost-Londen). In de zestiende eeuw was het eigendom van Henry VIII (die van die zes vrouwen) als uitvalsbasis voor zijn jachtactiviteiten. Begin negentiende eeuw werd het een pub. Naast de pub lag een cricketveld. The Old Spotted Dog was een chique pub. In 1888 ging Clapton FC op het veld naast de pub spelen en het stadion kreeg ook de naam The Old Spotted Dog. Het was vroeger een heel aardig stadionnetje. Een van de tribunes had de naam The Dog Kennel Stand, erg mooi. Maar in de loop der jaren is Newham verpauperd en ook het stadion en de pub raakten steeds meer vervallen. In 2004 sloot de pub zijn deuren en met houten platen voor de deuren en ramen, ziet het er helemaal naargeestig uit. Het stadion is er nog wel, maar alle oude tribunes zijn verdwenen en wat er nu staat is een allergaartje. In de pub spuiten junks zich regelmatig vol met heroïne en het stadion wordt door de buurtbewoners gebruikt als sluikstortplaats. Het is eeuwig zonde dat zo’n legendarische pub en stadion zo aan het vervallen zijn.

.row
  .span12
    %h2 Wie zijn wij

.row
  .span12.about
    .about_section
      %p John is 38 jaar en woont in Eindhoven. Aangezien hij daar op juichafstand van het Philips Stadion woont, noemt hij zich PSV supporter, maar dan de teletekst/leunstoel variant. Zijn echte passe is Brits voetbal en sinds hij eind december 2002 voor het eerst Charlton Athletic bezocht op The Valley, was hij definitief verslaafd. Sindsdien is hij zo'n veertig keer bij The Addicks geweest. Buiten zijn liefde voor Charlton is John ook een Anglofiel en helemaal gek van groundhopping in de UK. Hij bezocht al 200 wedstrijden in Engeland, Schotland, Noord-Ierland en Ierland. Zijn favoriete grounds zijn Hillsborough van Sheffield Wednesday en Cappielow Park van Greenock Morton. De laatste jaren gaat zijn interesse steeds meer uit naar de Non-League, vanwege de typische Britse cultuur die je daar nog aantreft. Ondanks dat hij al veel wedstrijden heeft bezocht, is zijn droom nog niet uitgekomen en dat is een play-off finale van Charlton op Wembley, waarin The Addicks in de laatste minuut de 5-4 maken.

      %p
        Website:
        = link_to "MyGroundhops", "mygroundhops.herokuapp.com", target: 'blank'
        |
        Twitter:
        = link_to "@DutchAddick", "https://twitter.com/DutchAddick", target: 'blank'

.row
  .span12.about
    .about_section
      %p Joris is 34 jaar en woont in Tilburg. Uiteraard doet hij aan ‘support your local’ en is hij dus groot fan van Willem II. In de UK is hij voor Celtic, maar heeft hij pas een wedstrijd of twintig gezien van The Bhoys. Joris is dan ook meer een groundhopper dan clubfan in de UK, vandaar dat hij al bijna 200 verschillende stadions in de UK heeft gezien en komend seizoen de ‘92’ gaat voltooien. In Engeland volgt hij Sheffield Wednesday met meer dan gemiddelde interesse en voor een groot aantal Non-League clubs heeft hij een zwak, met name Workington en Marlow. Stadions waar hij graag komt zijn Hillsborough, Fratton Park (Portsmouth), Goodison Park (Everton), The Rec (Aldershot) en zo zijn er nog veel meer. Als derbyliefhebber zijn de derby’s van Bristol, Stoke-on-Trent en Ayr v Kilmarnock nog wedstrijden die hij ooit wil zien.

      %p
        Website:
        = link_to "DoingThe116 Blog", "http://doingthe116.wordpress.com/", target: 'blank'
        |
        Twitter:
        = link_to "@DoingThe116", "https://twitter.com/DoingThe116", target: 'blank'

app/views/frenzy/index.html.haml
- if can? :administrate_frenzy, Frenzy
  .row
    .span12
      %h3= I18n.t('frenzy.switch_participation')
      = form_tag frenzy_switch_participation_path do
        - if @settings.participation == true
          = hidden_field_tag :participation, false
          = submit_tag :submit, value: I18n.t('frenzy.participation_off'), class: 'btn'
        - else
          = hidden_field_tag :participation, true
          = submit_tag :submit, value: I18n.t('frenzy.participation_on'), class: 'btn'

  .row
    .span12
      %h3= I18n.t('frenzy.process_gameround')
      = form_tag frenzy_process_gameround_path do
        = select_tag 'gameround_id', options_for_select(Gameround.not_processed.map{ |g| ["#{markup_gameround(g)}", g.id] }, include_blank: true)
        = submit_tag :submit, value: I18n.t('frenzy.process'), class: 'btn'

  .row
    .span12
      %h3= I18n.t('frenzy.switch_period')
      = form_tag frenzy_switch_period_path do
        = submit_tag :submit, value: I18n.t('frenzy.switch_period'), class: 'btn'

  .row
    .span12
      %h3= I18n.t('frenzy.cancel_jokers')
      = render "cancel_jokers"

app/views/frenzy/rules.html.haml
.row
  .span3
    %ul.nav.nav-list
      %li.nav-header= I18n.t('.frenzy.rules.title')
      %li{ class: "#{'active' if params[:section] == 'participation'}"}
        = link_to I18n.t('.frenzy.rules.participation_title'), frenzy_rules_path(section: "participation")
      %li{ class: "#{'active' if params[:section] == 'points'}"}
        = link_to I18n.t('.frenzy.rules.points_title'), frenzy_rules_path(section: "points")
      %li{ class: "#{'active' if params[:section] == 'jokers'}"}
        = link_to I18n.t('.frenzy.rules.jokers_title'), frenzy_rules_path(section: "jokers")
      %li{ class: "#{'active' if params[:section] == 'gamerounds'}"}
        = link_to I18n.t('.frenzy.rules.gamerounds_title'), frenzy_rules_path(section: "gamerounds")
      %li{ class: "#{'active' if params[:section] == 'transfers'}"}
        = link_to I18n.t('.frenzy.rules.transfers_title'), frenzy_rules_path(section: "transfers")
      %li{ class: "#{'active' if params[:section] == 'small'}"}
        = link_to I18n.t('.frenzy.rules.small_title'), frenzy_rules_path(section: "small")

  .span9
    - case params[:section]
    - when 'participation'
      %h3= I18n.t('.frenzy.rules.participation_title')
      %p= I18n.t('.frenzy.rules.intro')
      %p= I18n.t('.frenzy.rules.participation1')
      %p= I18n.t('.frenzy.rules.participation2')
      %p= I18n.t('.frenzy.rules.participation3')
      %p= I18n.t('.frenzy.rules.participation4')
      .points
        = image_tag('scores.png')
    - when 'points'
      %h3= I18n.t('.frenzy.rules.points_title')
      %p= I18n.t('.frenzy.rules.points1')
      %ul
        %li= I18n.t('.frenzy.rules.points_score1')
        %li= I18n.t('.frenzy.rules.points_score2')
        %li= I18n.t('.frenzy.rules.points_score3')
        %li= I18n.t('.frenzy.rules.points_score4')
        %li= I18n.t('.frenzy.rules.points_score5')
      %p= I18n.t('.frenzy.rules.points_example1_title')
      %pre= I18n.t('.frenzy.rules.points_example1')
      %p= I18n.t('.frenzy.rules.points_example2_title')
      %pre= I18n.t('.frenzy.rules.points_example2')
    - when 'jokers'
      %h3= I18n.t('.frenzy.rules.jokers_title')
      %p= I18n.t('.frenzy.rules.jokers1')
      %p= I18n.t('.frenzy.rules.jokers2')
      %p= I18n.t('.frenzy.rules.jokers3')
      %ul
        %li= I18n.t('.frenzy.rules.jokers_period1')
        %li= I18n.t('.frenzy.rules.jokers_period2')
        %li= I18n.t('.frenzy.rules.jokers_period3')
        %li= I18n.t('.frenzy.rules.jokers_period4')
    - when 'gamerounds'
      %h3= I18n.t('.frenzy.rules.gamerounds_title')
      %p= I18n.t('.frenzy.rules.gamerounds1')
      %p= I18n.t('.frenzy.rules.gamerounds2')
    - when 'transfers'
      %h3= I18n.t('.frenzy.rules.transfers_title')
      %p= I18n.t('.frenzy.rules.transfers1')
      %p= I18n.t('.frenzy.rules.transfers2')
      %p= I18n.t('.frenzy.rules.transfers3')
    - when 'small'
      %h3= I18n.t('.frenzy.rules.small_title')
      %p= I18n.t('.frenzy.rules.small1')
      %p= I18n.t('.frenzy.rules.small2')
      %p= I18n.t('.frenzy.rules.small3')
      %p= I18n.t('.frenzy.rules.small4')